const CONFIGS = {
    link : "data/demo.json",
    lang: "ru",
    map: {
        world: {
            link: "http://your_map.com/",
            prefix: "world",
            mapname: "surface",
            zoom: 8,
            enable: true
        },
        world_nether: {
            link: "http://your_map.com/",
            prefix: "world_nether",
            mapname: "surface",
            zoom: 8,
            enable: true
        },
        world_the_end: {
            link: "http://your_map.com/",
            prefix: "world_the_end",
            mapname: "surface",
            zoom: 8,
            enable: true
        }
    }
};

const BACKGROUND = [
    "emerald",
    "diamond",
    "gold",
    "iron-ore",
    "acacia-wood",
    "andesite",
    "bookshelf",
    "bricks",
    "cactus",
    "chest",
    "coal-ore",
    "crafting-table",
    "diamond-ore",
    "dispenser",
    "diorite",
    "furnace",
    "glowstone",
    "gold-ore",
    "grass",
    "hay",
    "lava",
    "lazuli",
    "leaves",
    "magma",
    "melon",
    "moss-stone",
    "mushroom",
    "mycelium",
    "nether-brick",
    "netherrack",
    "note-block",
    "observer",
    "obsidian",
    "piston",
    "podzol",
    "prismarine",
    "pumpkin",
    "purpur",
    "quartz",
    "granite",
    "redstone",
    "redstone-lamp",
    "sand",
    "sandstone",
    "sea-lantern",
    "slime",
    "soul-sand",
    "sponge",
    "tnt",
    "water",
    "stone",
    "spruce-wood",
    "bedrock",
    "birch-wood",
    "bone",
    "end-stone"
];